.github/workflows/deploy_git_tag.yml, .github/workflows/deploy_npm.yml, .github/workflows/promote.yml, .releaserc.json, scripts/deploy-code.sh, scripts/update-version.sh
Work done to match the deployment process https://github.com/customerio/mobile/blob/levi/deploy-docs/GIT-WORKFLOW.md
=> ci: allow manually deploying code 

android/build.gradle, android/src/main/java/com/customerioreactnative/CustomerioReactnativeModule.kt, android/src/main/java/com/customerioreactnative/Extensions.kt
Support for Android in the package
=> feat: android updates in package

customerio-reactnative.podspec, ios/CustomerioReactnative.m, ios/CustomerioReactnative.swift, src/CustomerioTracking.tsx
closes https://github.com/customerio/issues/issues/7831
closes https://github.com/customerio/issues/issues/7426
Upgrade the iOS SDK version & add user-agent support in the package to differentiate the traffic coming from react native platform.
=> feat: user-agent updates in package

customerio-reactnative.podspec, ios/CustomerioReactnative.m, ios/CustomerioReactnative.swift, src/CustomerioConfig.tsx, src/CustomerioTracking.tsx, src/index.tsx
closes https://github.com/customerio/issues/issues/7898
This PR provides support for in-app messages in react native package and is par at iOS as of now.
=> feat: in-app functionality in react native package

customerio-reactnative.podspec
updating ios sdk version in podspec
=> feat: updating ios sdk version in podspec

package.json
=> feat: update package version

package.json
Reverts customerio/customerio-reactnative#22
=> revert: update package version

android/gradle.properties
- Updated Android SDK version to latest stable release `3.0.0`
=> chore: android sdk version updated to 3.0.0

android/gradle.properties, customerio-reactnative.podspec
Updating gist dependency version
=> fix: updating gist dependency version

customerio-reactnative.podspec
=> fix: updated ios sdk to 1.2.2

customerio-reactnative.podspec
Upgrade to latest iOS Version 1.2.6
=> fix: ios sdk latest version

.github/workflows/pr_lint.yml, customerio-reactnative.podspec
Upgraded iOS SDK version to latest stable 2.0.0
=> fix!: bumped ios version to 2.0.0

.github/workflows/deploy_git_tag.yml, .github/workflows/deploy_npm.yml, .github/workflows/promote.yml
Changes the Slack channel for deployment messages to the new mobile-deployments channel Refs customerio/issues#9014
=> ci: changes Slack deployment message channel

.github/workflows/deploy_git_tag.yml, .github/workflows/deploy_npm.yml, .github/workflows/promote.yml, android/src/main/java/io/customer/reactnative/sdk/CustomerIOReactNativeModule.kt, ios/CustomerioReactnative.m, ios/CustomerioReactnative.swift, src/CustomerioTracking.tsx
(Re:) https://github.com/customerio/issues/issues/8961
This feature provides flexibility to the user to users to register device token from the package using javascript function call.
Ami app test branch - https://github.com/customerio/amiapp-reactnative/pull/41
This PR is co-authored by: @Shahroz16
=> fix: register device token using react native package

CODE_OF_CONDUCT.md, README.md
Do we allow contributions? Is this this enough info? Too much/too little?
=> docs: add info from the docs/getting-started page to readme

README.md, docs/dev-notes/DEVELOPMENT.md
Related: https://github.com/customerio/amiapp-reactnative/pull/42, https://github.com/customerio/mobile/pull/6
- Added docs for testing SDK locally (Linked with Ami App for complete details)
- Updated README to align with other repositories
**NOTE:** I'll update any branch specific links to default just before merging
=> docs: setting up local environment

.vscode/settings.json, scripts/bootstrap.js, src/CustomerIOInAppMessaging.tsx, src/CustomerioConfig.tsx, src/CustomerioEnum.tsx, src/CustomerioTracking.tsx, src/index.tsx, src/types/PushPermissionStatus.tsx, src/types/index.tsx
- Fixed `eslint` issues by running `yarn lint --fix `
- Fixed `eslint` warnings for equality operators
- Added Visual Studio Code settings file to auto format when saving code files
=> style: fix eslint issues and warnings

android/src/main/java/io/customer/reactnative/sdk/CustomerIOReactNativeModule.kt
While working on a few other fixes, I realized we were caching Android SDK instance locally in ReactNative module which looked unnecessary now and could be replaced with Native Android SDK call. So I updated the code to remove the local instance without changing business logic.
- Replaced local instance of Android SDK with property referring to `CustomerIO.instance()` in native Android SDK
=> refactor: remove local instance reference

package.json, src/CustomerIOPushMessaging.tsx
closes: https://github.com/customerio/customerio-reactnative/issues/161
=> fix: gist migration and crash fix

Apps/.gitignore, Apps/APN/App.js, Apps/APN/ios/AppDelegate.mm, Apps/APN/ios/Env.swift.example, Apps/APN/ios/MyAppPushNotificationsHandler.swift, Apps/APN/ios/NotificationServiceExtension/NotificationService.m, Apps/APN/ios/NotificationServiceExtension/NotificationServicePushHandler.swift, Apps/APN/ios/Podfile.lock, Apps/APN/ios/SampleApp.xcodeproj/project.pbxproj, Apps/APN/src/components/Button.js, Apps/APN/src/components/SwitchField.js, Apps/APN/src/components/Text.js, Apps/APN/src/components/TextField.js, Apps/APN/src/screens/Attributes.js, Apps/APN/src/screens/CustomEvent.js, Apps/APN/src/screens/Dashboard.js, Apps/APN/src/screens/Login.js, Apps/APN/src/screens/Settings.js, Apps/APN/src/services/CustomerIOService.js
part of: https://github.com/customerio/issues/issues/8965
helps: https://github.com/customerio/issues/issues/9968
- Added listener for in-app messaging events
- Set `accessibilityLabel` for widgets so they can be located using `content-desc` by Appium
- Updated Podfile
- Initialize iOS SDK from native code
=> chore: set appium tags for apn sample

Apps/APN/android/build.gradle, Apps/APN/src/screens/Login.js, Apps/APN/src/services/CustomerIOService.js, README.md, android/build.gradle
helps: https://github.com/customerio/issues/issues/8965
- Removed unnecessary gist url from package
- Removed unnecessary gist url from sample app
- Fixed config variable reference
- Trimmed email on login screen
=> refactor: remove gist repo url

Apps/FCM/src/services/CustomerIOService.ts
part of: https://github.com/customerio/issues/issues/10909
- Fixed attributes map creation
- Fixed warnings for `undefined` fields in stored sdk config
=> chore: fcm sample fixes 

package.json, yarn.lock
Also fixes, 
- Filter automatic screen view tracking events (https://github.com/customerio/customerio-ios/issues/367)
- Cache queue inventory for lower CPU usage while running queue (https://github.com/customerio/customerio-ios/issues/368)
=> fix: added url path encoding

.github/dependabot.yml
- Added Dependabot configuration to monitor GitHub Actions.
- Set to check updates daily and auto-create PRs for any found updates.
- Keeps our actions updated and secure.
- Automates maintenance, reducing manual effort.
=> ci: added dependabot config

.github/workflows/deploy-sdk.yml
See https://github.com/customerio/customerio-flutter/pull/92
=> ci: use latest version of deploy tool

android/gradle.properties, package.json
Includes:
- https://github.com/customerio/customerio-android/releases/tag/3.6.7 
- https://github.com/customerio/customerio-ios/releases/tag/2.8.4
=> fix: in-app positioning issue

package.json
Deploys [iOS bug fix](https://github.com/customerio/customerio-ios/pull/399) as RN customers are effected by this bug.
=> fix(ios): memory exception during SDK initialization async tasks

src/CustomerioConfig.tsx, src/CustomerioTracking.tsx, tsconfig.json, yarn.lock
closes: [[CDP] RN iOS: Update CIO SDK to utilize Segment#11654](https://github.com/customerio/issues/issues/11654)
- Create and configure the Segment analytics object
- Route all API calls to the Segment analytics object instead of native
This pull request merges into `cdp_fork_integrate_segSDK`.
=> feat: configuring segment and sourcing calls to segment 

Apps/FCM/ios/Podfile.lock, android/gradle.properties
helps: [MBL-229 : Proguard rules for Android](https://linear.app/customerio/issue/MBL-229/proguard-rules-for-android)
What it does:
Bumps the android SDK version
=> fix: added proguard rules for R8 strict mode

Apps/APN/src/services/CustomerIOService.js, Apps/FCM/src/services/CustomerIOService.ts
Linear ticket: https://linear.app/customerio/issue/MBL-502/track-lifecycle-events-for-ios-rn-applications
Milestone 3 - Lifecycle events (iOS and Android) 
This PR has minor fixes as required in sample apps for the feature `trackApplicationLifecycleEvents`
=> chore: sample app fixes for application lifecycle track events

.github/workflows/deploy-sdk.yml, android/gradle.properties, android/src/main/AndroidManifest.xml, android/src/main/res/values/customer_io_config.xml, scripts/update-version.sh
part of [MBL-522](https://linear.app/customerio/issue/MBL-522/user-agent-rn-android)
- Used snapshot build from feature branch for Android SDK until native release is rolled out publicly
- Included SDK source and version so Android native SDK generates user agent based on it
- Updated `update-version` script to sync SDK client version in Android XML files with React Native package version
```
Customer.io ReactNative Client/3.8.0 (Google sdk_gphone64_arm64; 33) io.customer.rn_sample.fcm/1.0
```
=> chore: android user agent client source

android/src/main/java/io/customer/reactnative/sdk/CustomerIOReactNativeModule.kt
Linear ticket: https://linear.app/customerio/issue/MBL-534/add-push-notification-specific-methods-in-package
- Added `pushClickBehaviorAndroid` configuration in Android native module.
TODO - Change base branch to `feature/cdp-main` before merging
=> chore: android push click behaviour

.github/workflows/build-sample-apps.yml, Apps/APN/src/services/CustomerIOService.js, Apps/FCM/src/services/CustomerIOService.ts, package-lock.json
- Updated workflow to add newly required keys after CDP changes
- Fixed code to use stored values instead of hardcoded ones
- [Slack discussion](https://customerio.slack.com/archives/C01QYDKD0SU/p1727446209129269)
=> build: fix sample apps keys

Apps/FCM/ios/Podfile.lock, Apps/FCM/package-lock.json, Apps/FCM/package.json, package.json
Linear ticket: https://linear.app/customerio/issue/MBL-580/firebase-110-support-on-v2-version-of-ios-sdk
Uses iOS SDK version 2.14.2 that supports latest version of Firebase dependency.
=> fix: firebase version upgrade

Apps/APN/ios/Podfile, Apps/APN/ios/Podfile.lock, Apps/APN/ios/SampleApp.xcodeproj/project.pbxproj, Apps/APN/package-lock.json, Apps/FCM/ios/Podfile, Apps/FCM/ios/Podfile.lock, Apps/FCM/package-lock.json, android/src/main/java/io/customer/reactnative/sdk/CustomerIOReactNativeModule.kt, android/src/main/java/io/customer/reactnative/sdk/constant/Keys.kt, android/src/main/res/values/customer_io_config.xml, ios/wrappers/CioRctWrapper.mm, ios/wrappers/CioRctWrapper.swift, package-lock.json, src/customerio-cdp.ts, yarn.lock
part of [MBL-540](https://linear.app/customerio/issue/MBL-540/react-native)
- Updated native methods to receive SDK arguments for package info
- Updated native iOS SDK initialization to override `SdkClient` before initializing native iOS SDK
- Updated TS SDK initialization to pass package info when calling native SDKs for initialization
- Updated lock files
=> chore: fix iOS apps user agent

package.json
This PR bumps iOS SDK version to `3.5.1` that includes fix to dismiss keyboard when an in-app message appears, to allow uninterrupted user interaction.
This will help close https://github.com/customerio/customerio-reactnative/issues/176 github issue.
https://github.com/user-attachments/assets/e4928888-40a8-41ea-b229-d6fc78857665
=> fix: dismisses keyboard when an in-app message appears

Apps/APN/Gemfile.lock, Apps/APN/ios/Podfile.lock, Apps/APN/package-lock.json, Apps/FCM/ios/Podfile.lock, Apps/FCM/package-lock.json, package-lock.json, yarn.lock
part of: [MBL-642](https://linear.app/customerio/issue/MBL-642/crash-on-react-native-0761)
- Updated lock files to simplify reviews for upcoming PRs by removing unnecessary changes
=> chore: update lock files

android/gradle.properties, package.json
iOS updated to 3.8.1
Android updated to 4.5.5
=> fix: Updated version of native SDKs

package.json
Aligning it with iOS and Expo for consistency
=> chore: package author

android/build.gradle, src/customerio-push.ts, src/postInstall.js
This PR adresses outstanding lint warnings. No functional change.
The warnings in files under the `Apps` folder are intentionally left out as the code under this folder is planned to be removed
---
* #414
* #413
* #412
* #411
* #410
* #408 
* 👉 #409
=> chore: minor linting

src/index.ts
=> feat: introducing dump function

example/Gemfile.lock, example/package-lock.json, package-lock.json, package.json
- iOS SDK is improved with a no-swizzling system for Notification integration
- This updates the iOS SDK version to enable a no-swizzling system
- The easiest way to get a device token is to copy from the Xcode console
- Basic PN:
- Expectation: This will send the default testing PN, which should work in & out of the app
- Triggering:
- APN: Send test PN from 
-  PN with Deep-link:
- Expectation: This will send the PN payload with URL (google.com), which should work in & out of the app, and the tap should open this URL in Safari or Google app
- Triggering:
- APN: Use the button `Send test...` in the test-campaign PN-config from [https://fly.customer.io/workspaces/122348/journeys/composer/actions/196](https://fly.customer.io/workspaces/122348/journeys/composer/actions/196)
=> feat: Version updated to include no-Swizzling system from iOS SDK

.github/workflows/auto-update-native-sdks.yml
Adds automation to monitor and update Customer.io native SDK versions, eliminating manual tracking and ensuring timely updates.
- **Daily automation** checks for new iOS/Android SDK releases
- **Auto-creates PRs** with version updates and release notes
- **Manual trigger** support via GitHub Actions UI
=> ci: add automated native SDK version management

android/src/main/java/io/customer/reactnative/sdk/logging/NativeCustomerIOLoggingModuleImpl.kt
Closes: [MBL-1342](https://linear.app/customerio/issue/MBL-1342/crash-on-android-device-using-rn-sdk)
Some reports of crashes happening inconsistently on Android devices.
Our `NativeCustomerIOLoggingModuleImpl` sets up the logging dispatcher when its initialized, being a static object, the first reference of the class, causes this initialization to happen.
The theory is that a race condition happens and sometimes a log event comes before RN Trubo modules are fully initialized.
Delay setting the logging events dispatcher till the logging module is asked to be initialized.
=> chore: Prevent Android crash due to race condition during logging module initialization
