- ios/CustomerioReactnative.m
- ios/CustomerioReactnative.swift
- src/CustomerioTracking.tsx
closes https://github.com/customerio/issues/issues/7791
Android SDK allows setting up config only during initialisation, but iOS SDK allows config setup later on too. To maintain consistency on both the platforms, react native package now allows setting up config on initialisation which is same for both the platforms.
> fix: change in way to update config in ios

- android/src/main/java/io/customer/reactnative/sdk/CustomerIOReactNativeInstance.kt
- android/src/main/java/io/customer/reactnative/sdk/CustomerIOReactNativeModule.kt
- android/src/main/java/io/customer/reactnative/sdk/constant/Keys.kt
- android/src/main/java/io/customer/reactnative/sdk/storage/PreferencesStorage.kt
- customerio-reactnative.podspec
- ios/CustomerioReactnative.m
- ios/CustomerioReactnative.swift
- package.json
- src/CustomerioConfig.tsx
- src/CustomerioTracking.tsx
- Added support to differentiate between expo and react apps using `package.json`
- Added support for Expo client in iOS and Android SDK wrappers
- Updated iOS SDK to `1.2.1`
- Added `PackageConfig` to pass package configurations in a convenient way
> fix: support for expo client

- android/gradle.properties
- customerio-reactnative.podspec
This PR has iOS and Android SDK version updates
iOS - 2.0.0-alpha.1
Android - 3.2.0-alpha.1
iOS has some breaking changes but doesn't seem to be affecting react native package as we are already using shared instances and new method to initialise the package.
> fix: ios and android sdk version update

- .github/workflows/deploy_npm.yml
- scripts/deploy-code.sh
Closes: https://github.com/customerio/issues/issues/8747
There is an issue with the CI script that deploys to npmjs.com. 
The script today will push all deployments to "latest" tag which means that if we were to deploy an alpha or beta build of the RN SDK, that alpha or beta would be pushed to npmjs.com as "latest". This would not be good as that would easily allow customers to install alpha or beta by accident when they expected to use the "latest" production build. 
I modified the script to push to `next` npmjs tag for Alpha or beta builds. Otherwise, push to `latest`.
> ci: push to npm dist-tag other then latest for pre-releases

- .github/workflows/pr_lint.yml
The bot's ability to merge a PR by adding label Ready to merge has been causing issues lately because of the CI authentication problems all mobile repos have been experiencing. I am suggesting to remove the ability for a bot to merge a PR because GitHub now [offers a feature](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests) that removes the need for a bot to merge PRs for us
> ci: remove ci bot merge functionality

- android/gradle.properties
- android/src/main/java/io/customer/reactnative/sdk/CustomerIOReactNativeInstance.kt
- android/src/main/java/io/customer/reactnative/sdk/constant/Keys.kt
- customerio-reactnative.podspec
- ios/CustomerioReactnative.swift
- src/CustomerioConfig.tsx
- src/CustomerioTracking.tsx
Fixes: https://github.com/customerio/issues/issues/8990
- Removed `organizationId` from native wrappers
- Added `enableInApp` flag to enable/disable in-app messaging module
- Auto set `enableInApp` based on `organizationId` for existing customers
- Added appropriate warnings
- Updated native Android and iOS SDKs
> feat: deprecated organization id for in-app

- src/CustomerioTracking.tsx
Closes: https://github.com/customerio/issues/issues/9340
- Removed init method from SDK initialization to make it void
> fix: remove return from init

- android/build.gradle
- android/gradle.properties
I created a new sample app with React Native version `0.71.3`. But the app could not compile because of lower Kotlin version set in gradle than expected. I updated our React Native SDK to match the values with our Android SDK. However, if we found any customer facing issues with this change, we can suggest them to override kotlin version by adding the following to their `android/gradle.properties`
```
kotlinVersion=1.5.31
```
- Updated `kotlinVersion` in gradle props to [match with Android SDK](https://github.com/customerio/customerio-android/blob/beta/buildSrc/src/main/kotlin/io.customer/android/Versions.kt#L22)
- Updated `minSdkVersion` to [match with Android SDK](https://github.com/customerio/customerio-android/blob/beta/buildSrc/src/main/kotlin/io.customer/android/Configurations.kt#L4- …
> fix: kotlin version in gradle props

- .github/workflows/deploy-sdk.yml
The deploy-sdk action has two jobs. In the first, semantic-release will create a commit that bumps package.json, and then pushes to the `main` branch.
The second job will checkout the code and publish to npm. However, since it relies on $GITHUB_REF, it was checking out the original hash which didn't include the package.json bump.
> ci: fix github ref in npm publish step of deploy action

- android/gradle.properties
- android/src/main/AndroidManifest.xml
- android/src/main/java/io/customer/reactnative/sdk/CustomerIOReactNativeModule.kt
- android/src/main/java/io/customer/reactnative/sdk/CustomerIOReactNativePackage.kt
- android/src/main/java/io/customer/reactnative/sdk/messagingpush/PermissionStatus.kt
- android/src/main/java/io/customer/reactnative/sdk/messagingpush/RNCIOPushMessaging.kt
helps: https://github.com/customerio/issues/issues/8746
helps: https://github.com/customerio/issues/issues/9493
This PR includes changes for Android platform only. See #101 for more details.
- ~Updated target and compile SDK version to `33` as `POST_NOTIFICATIONS` permission is only available in SDK 33~ Replaced with permission constant
- Added `RNCIOPushMessaging` module to react package internally to keep all push related code separate from same module
- Added `PermissionStatus` for permission visibility and match with iOS
- Implemented method exposed in react native react native package for Android
**NOTE:** The expected results for methods exposed in react native should not change. If you notice anything that could create different results from changes in iOS, please point it out so …
> feat: push permission prompt [android]

- ios/CustomerioReactnative.swift
- src/CustomerioTracking.tsx
- src/index.tsx
- src/types/PushPermissionOptions.tsx
- src/types/PushPermissionStatus.tsx
- src/types/index.tsx
Add typescript definitions for a better development experience for typescript customers. 
PR needs tested in Ami app to confirm that the feature is working as intended. In particular, we need to test the new `PushPermissionStatus` type is populated on Android and iOS. 
The `PushPermissionStatus` is just a String. We have to test that both the Android and iOS ami apps result string when calling `getPushPermissionStatus` is one of the 3 hard-coded strings in `PushPermissionStatus`. 
Lastly for testing, we have to make sure that a RN app that uses Typescript will compile it's code while using this code change. With the branch `levi/typescript` of the Ami app, if you run `yarn tsc`, you will see that the only code that does not compile successfully is non-CIO SDK code. This makes me feel …
> fix: replace any data types with strongly typed objects

- ios/CustomerioReactnative.swift
- ios/CustomerioReactnative.xcodeproj/project.pbxproj
- ios/StringExtensions.swift
Closes: https://github.com/customerio/customerio-reactnative/issues/115
Alternative solution to [this pr](https://github.com/customerio/customerio-reactnative/pull/116). I decided to create a separate PR to demonstrate an idea that I had instead of modifying the branch in [this pr](https://github.com/customerio/customerio-reactnative/pull/116). 
It's recommended that only 1 PR is merged by the team.
> fix: native push permission status match typescript enum value

- android/src/main/java/io/customer/reactnative/sdk/CustomerIOReactNativePackage.kt
- android/src/main/java/io/customer/reactnative/sdk/extension/StringExt.kt
- android/src/main/java/io/customer/reactnative/sdk/extension/TypeConversion.kt
- android/src/main/java/io/customer/reactnative/sdk/messagingpush/RNCIOPushMessaging.kt
- src/CustomerIOPushMessaging.tsx
- src/CustomerioTracking.tsx
Closes: https://github.com/customerio/issues/issues/9591
- Added `CustomerIOPushMessaging ` in react native to keep push messaging features in a single class
- Registered `RNCIOPushMessaging ` as react native android module
- Added support to generate notification locally using `RemoteMessage` for FCM
> iOS currently doesn't implement `CustomerioPushMessaging` and resolves promise to `true` by default
For anyone receiving notifications outside Customer.io SDK, they can generate notifications locally using the following code snippet:
```
CustomerIO.pushMessaging().onMessageReceived(message).then(handled => {
// handled is true if notification was handled by Customer.io SDK; false otherwise
});
```
where `message` contains payload received using FCM.
An example using React Native Firebase …
> feat: process push notifications received outside CIO SDK

- android/build.gradle
- android/gradle.properties
- android/src/main/java/io/customer/reactnative/sdk/CustomerIOReactNativeModule.kt
fixes: https://github.com/customerio/issues/issues/9483
android sdk changes: https://github.com/customerio/customerio-android/pull/184
- Requested native SDK to trigger missed lifecycle events so messaging push listener can process notification payload
> fix: push opened metrics tracked on Android 12

- customerio-reactnative.podspec
This will need tested in Ami to confirm that our SDK is compatible with latest native iOS SDK. 
QA builds being created [over in the Ami RN github repo](https://github.com/customerio/amiapp-reactnative/pull/56)
iOS Ami RN app build to QA test with: `levi/auto-update-ios (1682348352)`
This PR updates the native iOS SDK version that is used by the RN SDK. In order for this PR to pass QA, we need to run the smoke test suite to confirm the SDK functionality is stable. This PR does not add any new features or bug fixes to the RN SDK. We simply need to test existing SDK functionality to assert that there are not issues.
> fix: autoupdate to latest major version of iOS SDK

- Apps/APN/package.json
- Apps/APN/yarn.lock
Change to allow our APN sample app to use local version of SDK instead of production version.
> refactor: APN sample app uses local SDK instead of production

- package.json
Release targeting to iOS version [2.7.1](https://github.com/customerio/customerio-ios/releases/tag/2.7.1)
> fix: iOS bad memory access crash

- Apps/APN/ios/Podfile
- Apps/APN/ios/Podfile.lock
- Apps/APN/ios/SampleApp.xcodeproj/project.pbxproj
- Apps/APN/yarn.lock
- package.json
This PR updates the RN SDK to point to the latest production version of iOS SDK. This is to install a bug fix release done today in the iOS SDK. 
No update to latest Android needed as we are already pointing at the latest version.
> fix: deinit cleanup repo bad memory access

- Apps/APN/android/app/build.gradle
- Apps/APN/android/app/src/main/AndroidManifest.xml
- Apps/APN/android/app/src/main/res/xml/network_security_config.xml
- Apps/APN/ios/Podfile.lock
- android/gradle.properties
Ships the latest Android SDK bug fix to RN customers.
> fix: in-app messages not displaying for release builds on Android

- Apps/APN/ios/Podfile
- Apps/APN/ios/Podfile.lock
- package.json
fixes: https://github.com/customerio/issues/issues/10475
- Updated iOS SDK to `2.7.7` which includes support to encode arrays recursively
> fix: support json array in attributes

- Apps/APN/ios/AppDelegate.mm
- Apps/APN/ios/MyAppPushNotificationsHandler.swift
- Apps/APN/ios/Podfile.lock
- Apps/FCM/ios/FCMSampleApp/AppDelegate.mm
- Apps/FCM/ios/FCMSampleApp/MyAppPushNotificationsHandler.swift
I proposed [changes to our SDK docs](https://github.com/customerio/docs/pull/1447) to increase the stability of `opened` push metrics for customers installing the RN SDK. 
This PR modifies the sample apps code to reflect the code snippets in the SDK docs PR.
> refactor: update samples to reflect SDK docs changes

- customerio-reactnative.podspec
The RN SDK today does require the messagingpush SDK module but the podspec that we ask customers to install does not include this module. This could mean compile-time errors. 
Yes, we do expect that customers setup rich push in their app and so we do not expect customers to encounter this problem. However, the idea that this PR also adds a comment to the podspec files specifying required dependencies is a good value add to the codebase. 
PR in draft mode and asks for review by team to get feedback if this is something we want to do or not. 
Note: Conversation that sparked this idea: https://github.com/customerio/docs/pull/1446#discussion_r1298239891
> fix: include required messagingpush dependency for no push configuration

- Apps/README.md
Create a readme doc on how to get started with building the sample apps. 
We have had conversations in slack on how to get the sample apps building after performing a fresh clone of the SDK source code. This doc is designed to help in that use case.
> docs: create sample app README for how to build the apps

- android/gradle.properties
version bump for: stack-overflow caused by BQ recursion (https://github.com/customerio/customerio-android/issues/251) ([365a5b6](https://github.com/customerio/customerio-android/commit/365a5b690ed37667dfb6782629ad56743d97904d))
> fix: stack-overflow caused by BQ recursion

- package.json
Ship [iOS bug fix](https://github.com/customerio/customerio-ios/pull/392).
> fix: remove BQ tasks register device with empty profile identifier

- package.json
Ship iOS bug fix https://github.com/customerio/customerio-ios/pull/397
**Note:** PR blocked until 2.8.5 iOS deployed to cocoapods.
> fix(ios): when queue cannot find task, expect queue runs next task

- Apps/APN/App.js
- Apps/APN/ios/AppDelegate.h
- Apps/APN/ios/Podfile.lock
- Apps/FCM/ios/FCMSampleApp/AppDelegate.h
- Apps/FCM/ios/FCMSampleApp/AppDelegate.mm
- Apps/FCM/ios/Podfile.lock
* Update the syntax of sample apps to align with [docs changes](https://github.com/customerio/docs/pull/1627). 
* APN app had an error at runtime. I fixed it with App.js changes. 
* Rest of files are caused because of running `pod update` in sample apps.
> refactor: update sample apps with newer RN syntax

- package.json
- src/CustomerioConfig.tsx
- src/CustomerioTracking.tsx
- tsconfig.json
- yarn.lock
Refers [[CDP] RN iOS: Fork & Integrate Segment React Native SDK #11653](https://github.com/customerio/issues/issues/11653)
This pull request gets merged into `main_cdp_rn` and not `main` to avoid releases before CDP work is complete and well tested. If anyone in the squad feels not aligned with this reason then please feel free to suggest a change.
> feat: using forked segment library in cio-rn package

- package.json
Install the latest iOS SDK version which includes automatic push click handling. Which gives the RN SDK great benefits such as: increased opened push metrics reliability and better compatibility with 3rd party RN push SDKs.
* [iOS feature deployed to production](https://github.com/customerio/customerio-ios/pull/403)
> feat: increase opened metrics reliability and 3rd party push SDK compatibility

- .github/workflows/test.yml
The github action that is used to process eslint results had a major version bump recently. They changed the way that you provide a github token used to create the CI status check.
For reference, here are docs for the latest version of this action:
https://github.com/ataylorme/eslint-annotate-action/tree/v3
> ci: fix eslint result processing

- Apps/APN/ios/Podfile.lock
- Apps/FCM/android/app/src/main/AndroidManifest.xml
- Apps/FCM/ios/Podfile.lock
- android/gradle.properties
- package.json
part of [MBL-127](https://linear.app/customerio/issue/MBL-127/on-call-customer-support)
- Updated native SDKs to latest stable release to include following changes
- enable logging for in-app (for iOS)
- use new header to set polling interval
- fixes an issue with multiple timers being scheduled
> feat: new header for polling interval and enable ios logging for in-app

- Apps/APN/ios/Podfile.lock
- package.json
part of: https://linear.app/customerio/issue/MBL-141/expo-50-with-version-100-beta15-crash-startup-app-on-ios
This PR is using iOS SDK's version `2.12.3` with the fix for this crash. Refer this [iOS PR](https://github.com/customerio/customerio-ios/pull/575) for more detail.
> fix: expo users reported app crash on didFailToRegisterForRemoteNotificationsWithError

- Apps/FCM/ios/NotificationServiceExtension/Info.plist
- Apps/FCM/ios/Podfile.lock
React native FCM sample app's NotificationServiceExtension does not compile. It was found that it throws an error in the console log on debugging the extension target. The error log is:
`__extensionPrincipalClass != nil - /Library/Caches/com.apple.xbs/Sources/ExtensionFoundation_Sim/ExtensionFoundation/Source/NSExtension/NSExtensionSupport/EXConcreteExtensionContextVendor.m:109: Unable to find NSExtensionPrincipalClass (NotificationServiceExtension.NotificationService) in extension bundle! Please verify that the extension links the required frameworks and that the value for NSExtensionPrincipalClass is prefixed with '$(PRODUCT_MODULE_NAME).' if the class is implemented in Swift.`
This is the same error that one of our customer experienced and the same that prevented the app to display …
> chore: fcm app not compiling and throws error on debugging

- .github/workflows/test.yml
Reverts https://github.com/customerio/customerio-reactnative/pull/240
The action that we use to parse eslint results had a major version release (`v3`) and then changed the release to `v3-beta`.
Until the project creates a git tag indicating more clearly that v3 is ready for prod, I think we should continue to use v2 to keep `main` CI checks passing.
commit-id:6e52990a
> ci: revert action that annotations eslint results to fix ci on main

- Apps/.gitignore
- Apps/APN/fastlane/Appfile
- Apps/APN/fastlane/Fastfile
- Apps/FCM/fastlane/Appfile
- Apps/FCM/fastlane/Fastfile
- Apps/fastlane/Fastfile
I realized recently that you cannot run `fastlane download_development_code_signing` in the sample apps here like you can in the iOS SDK. This commit adds fastlane functions into the project so you can run all `fastlane` commands that the apple-code-signing repository defines. Making local development a bit easier to do.
commit-id:4fef2365
> build: setup downloading code signing files for sample apps

- Apps/APN/ios/Podfile.lock
- Apps/APN/ios/SampleApp.xcodeproj/project.pbxproj
- Apps/FCM/ios/Podfile.lock
- package.json
Closes: https://linear.app/customerio/issue/MBL-190/release-react-native
This commit installs the latest version of the native iOS SDK which includes the new Apple privacy manifest files.
> feat: privacy manifest files

- Apps/APN/android/build.gradle
- Apps/FCM/android/app/src/main/AndroidManifest.xml
- Apps/FCM/android/build.gradle
- android/build.gradle
- android/gradle.properties
- android/src/main/AndroidManifest.xml
closes: [MBL-233](https://linear.app/customerio/issue/MBL-233/react-native-sdk-compatibility-with-gradle-8)
blocked by: release of https://github.com/customerio/customerio-android/pull/296
- Support for Android Gradle Plugin 8.0
- JDK Version is updated to `17` from `1.8`
- Updated react native package to make it compatible with changes for Android Gradle Plugin 8.0 in native SDK
- Updated sample app to include local and snapshot repos for testing
> feat: support for android gradle plugin 8

- Apps/FCM/babel.config.js
- Apps/FCM/ios/FCMSampleApp.xcodeproj/project.pbxproj
- Apps/FCM/ios/FCMSampleApp/AppDelegate.mm
- Apps/FCM/ios/FCMSampleApp/Info.plist
- Apps/FCM/ios/Podfile
- Apps/FCM/ios/Podfile.lock
- Apps/FCM/package.json
- Apps/FCM/tsconfig.json
part of: https://linear.app/customerio/issue/MBL-203/check-compatibility-of-rn-sdk-with-rn-v73
Updates FCM(iOS) sample app with latest (stable) react native version `0.73.6`. 
In case anyone of you wants to try out the upgrade and are having issues, I have listed down some troubleshoot topics [here](https://linear.app/customerio/issue/MBL-203/check-compatibility-of-rn-sdk-with-rn-v73#comment-e233ced5).
> chore: fcm ios sample app upgraded to 0.73.6

- Apps/APN/ios/Podfile.lock
- Apps/FCM/ios/Podfile.lock
- package.json
Part of: https://linear.app/customerio/issue/MBL-364/[bug]-push-notifications-not-showing-while-app-in-foreground-on-ios
A native iOS SDK bug is effecting RN customers who use `rnfirebase` FCM SDK alongside the CIO RN SDK. To understand the full details of the issues RN customers experience, see the native iOS PR: https://github.com/customerio/customerio-ios/pull/735
Testing:
* I installed the new iOS SDK v2 release in both of our RN sample apps and ran QA push regression tests against both apps. I reviewed the SDK logs when push events happened and noticed when our SDK forwarded events to `rnfirebase`, the push events were handled as we expect them to.
> fix: 3rd party SDK compatibility when SDK forwards push events back to us

- ios/wrappers/CioRctWrapper.swift
Regarding the [conversation](https://github.com/customerio/customerio-reactnative/pull/299#discussion_r1719679068) on the other PR: I updated the code but forgot to push it to the same [PR](https://github.com/customerio/customerio-reactnative/pull/299).
> chore: minor fix in identifying user

- android/src/main/java/io/customer/reactnative/sdk/CustomerIOReactNativeModule.kt
Linear ticket - https://linear.app/customerio/issue/MBL-453/[android]-update-native-module-to-use-identify-using-android-cdp-sdk
This PR addresses an issue with the Android native module’s identify method, correcting the code implementation to make sure it functions as expected.
> fix: fixed identify method in android native module 

- src/customerio-cdp.ts
Linear ticket : https://linear.app/customerio/issue/MBL-450/[android]-update-native-module-to-use-track-event-using-android-cdp
This PR updates react native package to use screen tracking without category as a parameter as per tech doc.
> chore: category not required in screen tracking in react native package

- ios/wrappers/CioRctWrapper.mm
- ios/wrappers/CioRctWrapper.swift
- src/customerio-cdp.ts
Linear ticket : [https://linear.app/customerio/issue/MBL-450/[android]-update-native-module-to-use-track-event-using-android-cdp](https://linear.app/customerio/issue/MBL-450/%5Bandroid%5D-update-native-module-to-use-track-event-using-android-cdp)
This PR updates react iOS native module to use screen tracking without category as a parameter as per tech doc.
> chore: category not required in screen tracking in ios native module

- android/src/main/java/io/customer/reactnative/sdk/CustomerIOReactNativeModule.kt
Linear ticket : https://linear.app/customerio/issue/MBL-453/[android]-update-native-module-to-use-identify-using-android-cdp-sdk
A user can be identified either by a user profile with an identifier or anonymously. An anonymous user is defined as one who provides traits without an identifier. The React Native package should be able to identify a user profile in either scenario. To support this functionality, both the iOS and Android native modules need to incorporate this feature. 
This PR adds support to anonymously identify a user when only traits are provided on Android Native module by updating the profile attributes. As no identifier is provided so the profile attributes are updated anonymously.
> chore: anonymously identify user profile when only traits are provided

- Apps/APN/src/services/CustomerIOService.js
- ios/wrappers/CioRctWrapper.swift
- ios/wrappers/logging/CioLoggingEmitter.mm
- ios/wrappers/logging/CioLoggingEmitter.swift
- src/customerio-cdp.ts
- src/native-logger-listener.ts
Linear ticket : https://linear.app/customerio/issue/MBL-477/add-logging-support-in-package-ios-and-react-native
As a developer, I want to have logging support integrated into the package so that I can easily access logs without needing to open Xcode.
Added logger support in React Native using event emitters from the iOS native module, enabling all native logs to be output to the React Native console. This eliminates the need for customers to open Xcode to retrieve logs, as they currently do.
> chore: logging feature in react native package and ios native module

- ios/wrappers/CioRctWrapper.mm
- ios/wrappers/CioRctWrapper.swift
- src/customerio-cdp.ts
Linear ticket:
https://linear.app/customerio/issue/MBL-505/register-and-delete-already-registered-device-token-in-react-native
https://linear.app/customerio/issue/MBL-506/register-and-delete-token-feature-support-in-ios-native-module
This PR introduces two new methods, `registerDeviceToken` and `deleteDeviceToken`, to both the React Native and iOS native modules. These methods have been implemented and tested to ensure proper functionality.
**React Native Module:**
- Added registerDeviceToken method.
- Added deleteDeviceToken method.
**iOS Native Module:**
- Implemented registerDeviceToken method.
- Implemented deleteDeviceToken method.
The purpose of these changes is to provide a more comprehensive device token management solution within the React Native and iOS native modules, enabling …
> chore: register and delete device token in react native & ios

- Apps/APN/src/screens/Settings.js
- Apps/APN/src/services/CustomerIOService.js
- Apps/FCM/src/services/CustomerIOService.ts
- ios/wrappers/utils/CioConfigUtils.swift
Linear ticket : https://linear.app/customerio/issue/MBL-508/automatic-device-token-and-attribute-collection-on-ios-and-android
As a developer, I need the ability to manually or automatically collect device tokens and set device attributes, either through manual input or automatically, so that these tokens and attributes can be consumed on Fly for building workflows. This feature would allow for more efficient device management and workflow automation based on device-specific data.
Added feature to auto track device attributes and made fixes for the feature wherever required.
> chore: auto register device attributes 

- android/src/main/java/io/customer/reactnative/sdk/messagingpush/RNCIOPushMessaging.kt
closes: [MBL-545: Push metrics tracking (iOS & Android - RN)](https://linear.app/customerio/issue/MBL-545/push-metrics-tracking-ios-and-android-rn)
uses exposed module config from native
> chore: reuses native module config

- Apps/APN/ios/Podfile
- Apps/APN/ios/Podfile.lock
- Apps/APN/package-lock.json
- Apps/FCM/ios/Podfile
- Apps/FCM/ios/Podfile.lock
- Apps/FCM/package-lock.json
- android/gradle.properties
- package.json
- yarn.lock
Remove the local paths and point to stable release with cdp support.
> chore: point to stable releases

- Apps/fastlane/helpers/build_helper.rb
This PR adds the Firebase Distribution groups for 'feature-branch', 'next', and 'public' in addition to the current 'all-builds' and 'stable-builds' groups.
> chore: update Fastfile to publish to new distribution groups

- ios/wrappers/push/CioRctPushMessaging.swift
This PR fixes an issue while building RN app based on 0.76.
| <img width="350" alt="image" src="https://github.com/user-attachments/assets/ddee065d-abfb-4943-b329-d08cd0abc912"> | <img width="350" alt="image" src="https://github.com/user-attachments/assets/889d7a24-9925-4768-aed0-e537eca641be"> |
|:-------------------------------------------------------------------------------------------------------------------:|---|
When calling the `trackNotificationResponseReceived` method via TurboModule for React Native, a compilation failure occurred at the parameter mapping stage between JavaScript and Swift/Objective-C. Debug logs revealed that the `trackNotificationResponseReceived:(NSDictionary *)payload` method was not recognized correctly because the arguments array was passed as null.
To …
> chore: TurboModule method signature mismatch in Swift by removing external parameter label

- ios/wrappers/CioRctWrapper.mm
- ios/wrappers/CioRctWrapper.swift
- ios/wrappers/inapp/CioRctInAppMessaging.mm
- ios/wrappers/inapp/CioRctInAppMessaging.swift
- ios/wrappers/logging/CioLoggingEmitter.mm
- ios/wrappers/logging/CioLoggingEmitter.swift
- ios/wrappers/push/CioRctPushMessaging.mm
- ios/wrappers/push/CioRctPushMessaging.swift
- ios/wrappers/utils/CioConfigUtils.swift
- ios/wrappers/utils/CioConstants.swift
fixes: [MBL-642](https://linear.app/customerio/issue/MBL-642/crash-on-react-native-0761)
- Added consistent `objc` annotations to all Swift methods used by Objective-C classes
- Formatted Swift code using the same formatter as native iOS codebase
- Formatted Objective-C code using [online formatter](https://formatter.org/objc-formatter) for consistency
> fix: compatibility with react native 0.76

- Apps/APN/ios/Podfile.lock
- Apps/APN/package-lock.json
- Apps/FCM/ios/Podfile.lock
- Apps/FCM/package-lock.json
- android/gradle.properties
- package-lock.json
- package.json
Upgrading the underlying CIO native SDKs to latest versions
> fix: Update native Android and iOS CIO SDK versions

- .github/workflows/build-sample-apps.yml
- Apps/fastlane/helpers/build_helper.rb
part of: [MBL-710](https://linear.app/customerio/issue/MBL-710/single-app-per-platform-distributed-to-firebase)
- Updated `Build Sample Apps` action to push only primary app to relevant channels
- Modified `get_build_test_groups` lane to decouple from GitHub and accept arguments for passing Firebase distribution groups when distributing sample apps
Please refer to linked ticket for detailed expectations regarding channel distribution.
> chore: build primary sample app

- Apps/APN/ios/Podfile.lock
- Apps/APN/package-lock.json
- Apps/APN/src/screens/Login.js
closes: [MBL-829](https://linear.app/customerio/issue/MBL-829/react-native-android-app-name-should-not-include-apn)
- Updated display name on Login screen for APN sample app on Android to "React Native" only
> chore: update display name for apn android

- .github/workflows/build-sample-apps.yml
- Apps/APN/env.sample.js
- Apps/APN/src/components/BuildInfoText.js
- Apps/APN/src/utils/build.js
part of [MBL-746](https://linear.app/customerio/issue/MBL-746/easy-to-understand-build-info)
- Updated CI workflow to include workspace name in build information
- Updated build info to match screenshot attached in linked ticket
- Added dedicated class and utility functions to primary sample app for easier modification and extraction of build info
| Local (with specific SDK version) |  CI (without specific SDK version) |
|-|-|
| ![img_local](https://github.com/user-attachments/assets/2180b933-2cd6-4e68-b5cd-c524c5291432) | ![img_ci](https://github.com/user-attachments/assets/e17ae82f-98ba-4f66-b4c8-6758c19b7be4) |
> chore: update sample app build info

- .github/workflows/build-release-sample-apps.yml
- .github/workflows/build-sample-app.yml
- Apps/fastlane/helpers/version_helper.rb
closes: [MBL-881](https://linear.app/customerio/issue/MBL-881/[react-native]-public-release-builds)
- Determined and passed correct branch name for public release builds
- Updated `generate_new_version` lane to include a fallback value in case the branch name cannot be determined
> chore: fix branch name for public release builds

- android/src/main/java/io/customer/reactnative/sdk/extension/MapExtensions.kt
- package-lock.json
This fixes: [MBL-982](https://linear.app/customerio/issue/MBL-982/[react-native][android]-sdk-fails-to-compile-with-react-native-078)
When building Android apps using our CIO RN SDK using latest RN version `0.78.x`, you get a compilation error:
```
error Failed to install the app. Command failed with exit code 1: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
e: file:/node_modules/customerio-reactnative/android/src/main/java/io/customer/reactnative/sdk/extension/MapExtensions.kt:6:12 Type mismatch: inferred type is 'kotlin.Any?', but 'kotlin.Any' was expected.
e: file:/node_modules/customerio-reactnative/android/src/main/java/io/customer/reactnative/sdk/extension/MapExtensions.kt:6:12 Return type mismatch: expected 'kotlin.collections.Map<kotlin.String, kotlin.Any>', actual …
```
> chore: Fix Android compilation error for RN 0.78.x

- .github/workflows/deploy-sdk.yml
`codeclimate/velocity-deploy-action` Github action started [failing](https://github.com/customerio/customerio-expo-plugin/actions/runs/14379532878/job/40319773344), which is blocking SDK release, we are temporarily disabling it to enables releasing
> chore: Remove Code Climate Velocity Deployment

- .github/workflows/build-release-sample-apps.yml
- .github/workflows/deploy-sdk.yml
Closes: [MBL-1053](https://linear.app/customerio/issue/MBL-1053/auto-create-testbed-releases-for-every-sdk-release)
This PR triggers a sample apps public release build after the SDK has been deployed successfully to NPM so that internal stakeholders always have up to date versions to test with.
> chore: Trigger sample apps public builds after npm deployment is successful

- .github/workflows/deploy-sdk.yml
Closes: [MBL-1053](https://linear.app/customerio/issue/MBL-1053/auto-create-testbed-releases-for-every-sdk-release)
I've made a mistake in the previous PR #403, reusable workflows should be called at the job level and not on the step level. Steps can only call custom action and not reusable workflows.
> chore: Fix Github workflow job triggering public sample app build for SDK releases

- package.json
This is a very old left over being corrected
> chore: package author

- customerio-reactnative-richpush.podspec
- example/package-lock.json
- package-lock.json
- yarn.lock
I ran into a scenario that attempts to link both APN and FCM dependencies and causing the `pod install` command to fail because they have different linkage requirements.
I am not sure what triggers this behavior, but I believe the issue is because the rich push specs doesn't have a default subspec.
This wasn't happening before, but now it is happening 100% of the time. Which makes me unsure what triggers it. But here are what reproduces it at the moment
```
npm i
cd example
npm run prepare
npm i
bundle install
```
After this try to use pod install for APN or FCM
```
PUSH_PROVIDER=fcm bundle exec pod install --project-directory=ios
bundle exec pod install --project-directory=ios
```
* When the env var `PUSH_PROVIDER=fcm` is set, Cocoapods should only install `CustomerIO/MessagingPushFCM` …
> fix: define default pod for the rich push pod

- example/Gemfile.lock
- example/package-lock.json
- package-lock.json
- package.json
- yarn.lock
In an earlier change, I set `"main": "./lib/modules/index.js"` instead of `"main": "./lib/commonjs/index.js"` which points to the wrong source for commonjs packages.
This PR fixes this change to point to the correct source. You can learn more about the dual package setup here: https://callstack.github.io/react-native-builder-bob/esm#dual-package-setup
```
npm run prepare
cd example
./scripts/sample-apps-init.sh
```
> fix: default to commonjs

- android/src/main/java/io/customer/reactnative/sdk/messaginginapp/BaseInlineInAppMessageViewManager.kt
- android/src/main/java/io/customer/reactnative/sdk/messaginginapp/ReactInAppPlatformDelegate.kt
- android/src/main/java/io/customer/reactnative/sdk/messaginginapp/ReactInlineInAppMessageView.kt
part of: [MBL-1188](https://linear.app/customerio/issue/MBL-1188/support-props-and-callbacks-on-android)
- Refactored `ReactInlineInAppMessageView` to inherit from shared `WrapperInlineView` for a smaller, simpler implementation
- Updated `ReactInAppPlatformDelegate` to extend `WrapperPlatformDelegate`, reducing duplication
- Used shared constants for event registration in `BaseInlineInAppMessageViewManager`
- Run example app and Inline Messages screen should work as expected on Android
- No behavior changes, messages should display correctly
> chore: utilize WrapperInlineView in android

- package.json
Seems like we've added `customerio-reactnative` dependency on itself by mistake [here](https://github.com/customerio/customerio-reactnative/pull/433/files)
This PR removes this
> chore: Remove RN SDK dependency on itself

- package.json
Update native iOS SDK to latest
> fix: Preserve numeric types when doing sanitization for JSON

- src/cio-config.ts
- src/customerio-cdp.ts
- src/specs/modules/NativeCustomerIO.ts
- src/utils/native-bridge.ts
- src/utils/param-validation.ts
part of: [MBL-1252](https://linear.app/customerio/issue/MBL-1252/create-turbomodule-typescript-specifications)
This is the first PR in the effort to migrate our React Native SDK to use React Native's new TurboModule architecture for native communication. This PR focuses solely on Data Pipelines (Main SDK) module. Future updates for Push and In-App modules will follow a similar structure.
- Added `NativeCustomerIO.ts`, a TurboModule specification with full Codegen support
- Refactored SDK public interface from a class based to an object based architecture, using strong TypeScript types for public API compliance with codegen
- Consolidated configuration types and enums into spec module to avoid redundancy
- Added improved error handling with validation and clear messaging
- Added native …
> chore: add TurboModule TypeScript support for Data Pipelines

- example/package-lock.json
- package-lock.json
- src/cio-config.ts
- src/customerio-cdp.ts
- src/index.ts
- src/native-logger-listener.ts
- src/specs/modules/NativeCustomerIO.ts
- src/types/data-pipelines.ts
- src/types/index.ts
- src/types/internal.ts
- src/utils/param-validation.ts
part of: [MBL-1254](https://linear.app/customerio/issue/MBL-1254/convert-customerio-datapipelines-to-turbomodule-ios)
Initially, types were exported from separate files but I earlier moved into Codegen spec for better alignment between internal and public APIs. However, Codegen generated types are only usable from Objective-C and not Swift friendly. This PR reverts that approach to simplify Codegen while cleanly maintaining a shared contract between native and TypeScript using dedicated export files.
- Reorganized type exports into modular files: `data-pipelines.ts`  (public API types), `internal.ts` (native/internal types)
- Improved native bridge type naming (e.g., renamed `CustomAttributes` to `NativeBridgeObject` in the spec for clarity)
- Added brief JSDoc comments for all public …
> chore: fix Data Pipelines TypeScript types exports

- android/gradle.properties
- example/android/app/src/main/AndroidManifest.xml
- example/package-lock.json
- package-lock.json
Closes: [MBL-730](https://linear.app/customerio/issue/MBL-730/react-native-enable-setting-android-message-channel-name)
This PR adds the ability for SDK customers to configure the messaging channel where CIO push notifications are shown for on Android Oreo and higher. There are 3 values that can be configured:
- `io.customer.notification_channel_id` - Custom channel identifier
- `io.customer.notification_channel_name` - Custom channel display name
- `io.customer.notification_channel_importance` - Channel importance level
If config are not provided, defaults are used to create a default channel
> feat: Add ability to configure messaging channels for local notifications

- src/customerio-inapp.ts
- src/specs/modules/NativeCustomerIOMessagingInApp.ts
- src/types/InAppMessage.ts
- src/types/in-app.ts
- src/types/index.ts
part of: [MBL-1257](https://linear.app/customerio/issue/MBL-1257/convert-inappmessaging-to-turbomodule-android), [MBL-1258](https://linear.app/customerio/issue/MBL-1258/convert-inappmessaging-to-turbomodule-ios)
This PR adds `TurboModule` TypeScript support for In-App messaging module as part of React Native New Architecture migration. The changes consolidate in-app related types and add proper `Codegen` compatible specifications for enhanced type safety.
- Added `NativeCustomerIOMessagingInApp.ts` TurboModule specification with proper TypeScript interfaces
- Consolidated push types into unified `in-app.ts` file, removing separate type files
- Updated `customerio-inapp.ts` to use TurboModule patterns and native bridge utilities
- Enhanced type imports across affected modules for better …
> chore: add TurboModule TypeScript support for InApp

- android/src/newarch/io/customer/reactnative/sdk/messaginginapp/NativeMessagingInAppModule.kt
- android/src/oldarch/io/customer/reactnative/sdk/messaginginapp/NativeMessagingInAppModule.kt
- example/src/App.tsx
- ios/wrappers/inapp/NativeMessagingInApp.mm
- src/customerio-cdp.ts
- src/customerio-inapp.ts
- src/native-logger-listener.ts
- src/specs/components/InlineMessageNativeComponent.ts
- src/specs/modules/NativeCustomerIO.ts
- src/specs/modules/NativeCustomerIOLogging.ts
- src/specs/modules/NativeCustomerIOMessagingInApp.ts
- src/specs/modules/NativeCustomerIOMessagingPush.ts
- src/utils/param-validation.ts
part of: [MBL-1261](https://linear.app/customerio/issue/MBL-1261/remove-legacy-bridge-code-and-update-dependencies)
- Unified `isNewArchEnabled` check by moving it to logger module which is a lightweight module that can be initialized early and independently
- Removed redundant `isNewArchEnabled` method from in-app module
- Fixed `CustomerIO.inAppMessaging.registerEventsListener` to avoid breaking changes
- Handled `Map` objects in `CustomAttributes` to ensure compatibility with JS Map (was broken in `main` too)
- Updated example app to register in-app message listeners
- Reverted `codegen` type imports to support compatibility with older versions of React Native and Expo
- [Slack discussion](https://customerio.slack.com/archives/C06H7MMLH6C/p1753424909705239?thread_ts=1753420118.217359&ci …
> chore: update TurboModule spec types import and clean up arch checks

- example/ios/SampleApp.xcodeproj.tracked/project.pbxproj
- example/package-lock.json
- package-lock.json
closes: [MBL-1241](https://linear.app/customerio/issue/MBL-1241/fix-react-native-example-app-crash-on-ios-devices)
Fixed iOS example app crashing on device with "No script URL provided" error when running builds on real devices.
- Added React Native bundle script to iOS project build phases
- Updated tracked Xcode project with "Bundle React Native code and images" build phase
- Uses standard React Native bundling scripts for automatic debug/release handling
- Release builds now work correctly on physical devices
- Debug builds continue to use Metro as expected
> chore: fix ios example app on real device

- .github/workflows/auto-update-native-sdks.yml
Fix duplicate PR creation in the auto-update native SDKs workflow by adding duplicate detection logic before creating new PRs.
Problem
The GitHub Actions workflow that automatically updates Customer.io native SDK versions was creating duplicate PRs daily. Even when a PR for the same SDK versions already existed, the workflow would create a new branch and PR every day at 9 AM UTC, resulting in spam and cluttered PR lists.
Solution
Added a duplicate detection step that:
- Checks for existing PRs before creating new branches using the exact title matching logic
- Searches by version numbers as a fallback to catch any Customer.io SDK update PRs with the same versions
- Skips all subsequent steps (branch creation, file updates, testing, PR creation) when duplicates are found
- Provides clear …
> ci: add check to avoid duplicate

- example/ios/NotificationServiceExtension/NotificationService.swift
- example/ios/Podfile
- example/src/App.tsx
- example/src/env.ts.sample
- package.json
part of: [MBL-1277](https://linear.app/customerio/issue/MBL-1277/react-native-sdk-443-conflict-with-facebook-login-sdk)
Upgraded native iOS SDK from `3.11.0` to `3.13.1` which includes following updates:
- Sticky session queue support
- Public API alignment
- Xcode 16 beta fixes
- Fixed deep link issues with FCM when using `CioAppDelegateWrapper`
- Updated example app `env.ts.sample` to properly support multiple keys (APN and FCM use cases)
- Fixed broken `env` fetching logic in `App.tsx`
- Set `logLevel` to `debug` in example app NSE
> feat: support for custom scheme link with fcm

- example/package-lock.json
- ios/wrappers/inapp/NativeMessagingInApp.swift
- ios/wrappers/inapp/ReactInAppEventListener.swift
- package-lock.json
part of: [MBL-1366](https://linear.app/customerio/issue/MBL-1366/fix-or-remove-react-native-ios-import-dependency-from-expo-plugin-auto)
Ensures `ReactInAppEventListener` is set when React Native messaging in app module is initialized. This improves support for expo auto initialized behavior by avoiding direct, early references to React classes that could cause import issues.
- Set `ReactInAppEventListener` during `initialize()` lifecycle of React Native messaging in app iOS module
- Updated listener's initialization to insert itself into shared dependency graph when accessed early, so it becomes accessible for auto initialization scenarios (e.g., Expo SDK starting before full UI render)
- In manual initialization setups, the listener is still registered during `CustomerIO.initialize()` …
> fix: update in-app module to set listener on initialize
